### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by alevangel** [martin-marek/parking-space-occupancy#1]
There is an issue of RAM during the training of the FasterRCNN_FPN on Colab. 

How to optimise the code?

**Comment by martin-marek** [comment]
The images in the dataset have resolution 4000x3000. In `RCNN`, image patches are first resized before being passed to the backbone. However, in `FasterRCNN_FPN`, there is no resizing. Unfortunately, you can't pass a 4000x3000 image to the backbone – you have to resize it. You can do that using the `res` keyword during training. Here's an [example](https://github.com/martin-marek/parking-space-occupancy/blob/2e7ee0b2bba80b736f5b9d180c82bcc581234e51/train_all_models.py#L31).

**Comment by alevangel** [comment]
Thanks

**Comment by martin-marek** [comment]
Did you manage to solve the problem? Based on the edit history of your comment, I see that you still encountered some issues.

**Comment by alevangel** [comment]
> Did you manage to solve the problem? Based on the edit history of your comment, I see that you still encountered some issues.

Yes. It was a problem with the GPU Ram not deleted. With the resolution of 800 it works.
