### ISSUE TITLE
How do I use my images in inference along with my rois? should it be in the same format as the dataset?

### ISSUE THREAD

**Issue by Prajwalabraham** [martin-marek/parking-space-occupancy#2]

**Comment by Prajwalabraham** [comment]
I was looking into inference using my custom images. But I am getting a lot of errors mostly because of not being in the desired format

**Comment by martin-marek** [comment]
Could you please share what errors specifically you're getting? I would assume that indeed they need to be in the same format.

As you can see from the readme, something like this should work:
```python
# inference
image = torch.zeros([3, 1000, 1000])
parking_space_coordinates = torch.zeros([10, 4, 2])
image = transforms.preprocess(image)
class_logits = model(image, parking_space_coordinates)
class_scores = class_logits.softmax(1)[:, 1]
```

**Comment by Prajwalabraham** [comment]
Sure. I was trying to give a custom image "pklot1.JPG" and the rois for that image as "rois.pkl"

The code to define the ROI:
[roi.txt](https://github.com/martin-marek/parking-space-occupancy/files/10911713/roi.txt)

the latest code for inference is:

# inference
#image = torch.zeros([3, 1000, 1000])
from PIL import Image
from torchvision import transforms

image_path = "one.JPG"
image = Image.open(image_path)
transform = transforms.Compose([
    transforms.Resize((1000, 1000)),
    transforms.ToTensor(),
])
image = transform(image)
image = image.unsqueeze(0)  # add batch dimension
import pickle

roi_file_path = "rois.pkl"
with open(roi_file_path, "rb") as f:
    rois = pickle.load(f)
rois = torch.tensor(rois)

parking_space_coordinates = rois
from utils import transforms

image = transforms.preprocess(image)
class_logits = model(image, parking_space_coordinates)
class_scores = class_logits.softmax(1)[:, 1]

vis.plot_ds_image(image, parking_space_coordinates, class_scores)   

The error I am currently getting is:

        ~~~~~~~~~~ <--- HERE
    c = c.repeat(1, 4, 1)
    c[:, 0, 0] += w/2
RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Int

The ones I usually get is: 
RuntimeError: The size of tensor a (3000) must match the size of tensor b (3) at non-singleton dimension 0
...
     31     width, height = img.size
     32     return [channels, height, width]
---> 33 raise TypeError(f"Unexpected type {type(img)}")

RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 8294400000000 bytes.


PS: I'm a bit new to this. So I'm not able to figure out in what format am i supposed to give as input and visualize on the image

**Comment by Prajwalabraham** [comment]
Actually i was able to give the proper inputs. But what output am I supposed to expect? i am not able to use 
vis.plot_ds_image(image, parking_space_coordinates, class_scores)   to visualize. and the output of the class_scores is tensor([2.8752e-05, 2.8752e-05, 2.8752e-05, 2.8752e-05, 2.8752e-05, 2.8752e-05,
        2.8752e-05, 2.8752e-05, 2.8752e-05, 2.8752e-05],
       grad_fn=<SelectBackward0>)

**Comment by martin-marek** [comment]
Hey, have you figured it out?

As you can see in `dataset/acpds.py`, I [load](https://github.com/martin-marek/parking-space-occupancy/blob/17da2c8b33055be8019483260f0efbcbdfda0478/dataset/acpds.py#L47) images using torchvision.

Also, I think that rois need to be in relative coordinates, scaled to [0, 1].

**Comment by Prajwalabraham** [comment]
Right. I figured it out. Yes i went through the acpds.py and was able to load the image using torch. And also the rois had issues in the format, i restructured the whole code and was able to get it worked. 

Thanks for the support :)

**Comment by martin-marek** [comment]
Great, I'm glad you got it working!
