### ISSUE TITLE
I couldn't access the dataset

### ISSUE THREAD

**Issue by tr-brain-com** [martin-marek/parking-space-occupancy#3]
Hello, I want to review your work but I couldn't access the dataset. Could you share the updated link of the dataset?

**Comment by martin-marek** [comment]
Hi, could you please clarify where you're trying to download the dataset from?

I have just tested the [link for the dataset](https://pub-e8bbdcbe8f6243b2a9933704a9b1d8bc.r2.dev/parking%2Frois_gopro.zip) in README and was able to download it.

**Comment by tr-brain-com** [comment]
hi, https://pub-e8bbdcbe8f6243b2a9933704a9b1d8bc.r2.dev/parking%2Frois_gopro.zip, thank you

**Comment by tr-brain-com** [comment]
I noticed something like this. I was able to download from my mobile phone while I couldn't download from my computer. I think it might be a firewall issue. I'm sorry for taking your time, thank you very much for your interest and concern.

**Comment by martin-marek** [comment]
No worries, I’m glad you got it working!
